import os
import httpx
import base64
import logging
from dotenv import load_dotenv
from ..core.config import settings

logger = logging.getLogger(__name__)

class TTSService:
    """Streams audio back as text chunks are received from LLM using Sarvam AI TTS (Bulbul model)."""

    def __init__(self, speaker="rehan", language="en-IN"): 
        # Default voice and regional accent settings
        self.speaker = speaker
        self.language = language

    async def stream_audio_from_text(self, text_chunk: str, language_code: str = None):
        """Yields audio bytes generated by Sarvam AI for a text chunk."""
        if not text_chunk.strip():
            return
            
        target_lang = language_code or self.language
            
        # Dynamically load .env on every TTS request so the user doesn't have to restart uvicorn
        env_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), ".env")
        load_dotenv(dotenv_path=env_path, override=True)
        self.api_key = os.environ.get("SARVAM_API_KEY", "")

        if not self.api_key or self.api_key == "your_sarvam_api_key_here":
            logger.error("SARVAM_API_KEY is missing! Voice will not play until it is added to .env.")
            return
            
        url = "https://api.sarvam.ai/text-to-speech"
        
        headers = {
            "Content-Type": "application/json",
            "api-subscription-key": self.api_key
        }
        
        data = {
            "inputs": [text_chunk],
            "target_language_code": target_lang,
            "speaker": self.speaker,
            "model": "bulbul:v3"
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(url, json=data, headers=headers)
                
                if response.status_code != 200:
                    logger.error(f"Sarvam AI TTS Error: {response.status_code} - {response.text}")
                    return
                
                # Success response from Sarvam AI
                json_response = response.json()
                audios = json_response.get("audios", [])
                
                if audios and isinstance(audios, list) and isinstance(audios[0], str):
                    base64_audio = audios[0]
                    # Decode base64 to binary wav bytes
                    wav_bytes = base64.b64decode(base64_audio)
                    yield wav_bytes
                else:
                    logger.error(f"Sarvam AI TTS returned unexpected format: {json_response}")
                    
        except Exception as e:
            logger.error(f"TTS Streaming Exception: {e}")
